spring:
  datasource:
    url: jdbc:h2:mem:tennisdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  application:
    name: reservation-service
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/liquibase-master.xml
    contexts: seed,prod

server:
  port: 8080

application:
  jwt:
    secret: 72f49e5265e83e07d350862da5eb0acaac6959e75eb0faebfe80baceb9bcc28a
    expiration-time : 86400000
    refresh:
      expiration-time : 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
