spring:
  datasource:
    url: jdbc:h2:mem:tennisdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  application:
    name: reservation-service
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/liquibase-master.xml

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
